/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/map/': RouteRecordInfo<'/map/', '/map', Record<never, never>, Record<never, never>>,
    '/map/scan/[id]': RouteRecordInfo<'/map/scan/[id]', '/map/scan/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/merchant/': RouteRecordInfo<'/merchant/', '/merchant', Record<never, never>, Record<never, never>>,
    '/merchant/create': RouteRecordInfo<'/merchant/create', '/merchant/create', Record<never, never>, Record<never, never>>,
    '/merchant/create-ai': RouteRecordInfo<'/merchant/create-ai', '/merchant/create-ai', Record<never, never>, Record<never, never>>,
    '/merchant/create-submit': RouteRecordInfo<'/merchant/create-submit', '/merchant/create-submit', Record<never, never>, Record<never, never>>,
  }
}
