version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    ports:
      - "4001:80"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
